### ISSUE TITLE
commit  9c44abab

### ISSUE THREAD

**Issue by GM-990** [OpenVisionE2/sh4-driver#3]
/git/avs/avs_core.c:101:0: error: unterminated #if
|  #if defined(HOMECAST5101)
git/avs/avs_core.c:100:1: error: expected expression at end of input
|  static unsigned short normal_i2c[] = {

**Comment by persianpros** [comment]
Thanks for the report, fixed: https://github.com/OpenVisionE2/sh4-driver/commit/e3ad0fdcfd923d4f618d0c6e9a868aa21a812560
