### ISSUE TITLE
the new cuberevo_micom.ko reports error

### ISSUE THREAD

**Issue by backup1977** [OpenVisionE2/sh4-driver#4]
Hello @persianpros 

the new cuberevo_micom.ko reports error, and the front display, and the remote control are not working.
the cuberevo_micom reports:

cuberevo_micom: Unknown symbol rtc_device_unregister
cuberevo_micom: Unknown symbol rtc_device_register
/etc/init.d/rc: /etc/rcS.d/S05modutils.sh: line 1: can not create / dev / vfd: No such device or address

and the evremote2 announces:

[evremote2 cuberevo] micom version = 694197418
[evremote2] Error in device initialization

####### log #######
VFS: Mounted root (ext2 filesystem) on device 8:1.
devtmpfs: mounted
Freeing unused kernel memory: 124k freed
copLoadFile (file /boot/video.elf)
ustslave: Kernel Version: 24
base_address 0x10000000
copLoadFile (file /boot/audio.elf)
ustslave: Kernel Version: 24
base_address 0x10400000

INIT: version 2.88 booting

lircd.conf missing!
Fuse filesystem already available.
Mounting fuse control filesystem.
sh: sda1: unknown operand
EXT4-fs (sda2): warning: mounting unchecked fs, running e2fsck is recommended
EXT4-fs (sda2): mounted filesystem without journal
EXT4-fs (sda3): warning: mounting unchecked fs, running e2fsck is recommended
EXT4-fs (sda3): mounted filesystem without journal
EXT4-fs (sda5): warning: mounting unchecked fs, running e2fsck is recommended
EXT4-fs (sda5): mounted filesystem without journal
EXT4-fs (sda6): mounted filesystem with ordered data mode
EXT4-fs (sda7): warning: mounting unchecked fs, running e2fsck is recommended
EXT4-fs (sda7): mounted filesystem without journal
cuberevo_micom: Unknown symbol rtc_device_unregister
cuberevo_micom: Unknown symbol rtc_device_register
/etc/init.d/rc: /etc/rcS.d/S05modutils.sh: line 1: can't create /dev/vfd: No such device or address
stmcore-display: STx7109c3 display: probed
device probe found 2 display pipelines
stmfb: fb0 parameters = "1280x720-32@50:16m:pal:cvbs:rgb:yuv"
stmfb: i2c_transfer failed with -6!!!
stmfb: i2c_transfer failed with -6!!!
stmfb: i2c_transfer failed with -6!!!
stmfb: fb1 parameters = "<NULL>"
stmfb: i2c_transfer failed with -6!!!
stmfb: i2c_transfer failed with -6!!!
stmfb: EDID Read Error, setup safe EDID
stmfb: Setting Safe EDID
Init of MME log wrapper
STx71XX MPEG2 hardware host transformer loaded
snd_pseudo snd_pseudo.0: firmware: requesting downmix.fw
pseudocard: 1 pseudo soundcard(s) found
socket_init >
socket_probe >
***************************
socket 1
name socket-1
pio port -1
pio pin -1
active l/h -1
i2c_bus 0
socket_probe <
socket_init < 0
lnbh221_init >
lnbpio_init >
cx24116_init >
cx24116_probe >
found frontend "cx24116" in platform config
cx24116_probe <
cx24116_init < 0
stv090x_init >
stv090x_probe >
found frontend "stv090x" in platform config
stv090x_probe <
stv090x_init < 0
starci2win loaded
pti: module license 'NO' taints kernel.
Disabling lock debugging due to kernel taint
pti loaded (videoMem = 4096, waitMS = 20, enableStatistic = 0)
no swts ->routing streams from dvr0 direct to the player
DVB: registering new adapter (STM Streamer)
0: DeviceContext 8b8ae088, DvbDemux 8b8ae38c, DmxDevice 8b8ae574
membase-0 0xa3000000
membase-1 0xa3010000
ptiInit context = 8b8ae088, demux = 8b8ae38c
[TSM] init stream routing...
Routing streams through cimax
Load real TC Code
TC_Data = b9238000, TC_Code = b923c000
Readback TC ... successfull
using videoMem = 770048 (packets = 4096)
pti: pti_buffer_pool_init: allocate 188 pages (770048 bytes)
DMA(0) base = 5580000, top = 563c000, buffer = 5580000, size 770048
freeBuffer(): free = 1
pti: pti_buffer_pool_init: allocate 188 pages (770048 bytes)
DMA(1) base = 563c000, top = 56f8000, buffer = 563c000, size 770048
freeBuffer(): free = 2
Validity = 0x0001 Mode = 0x0000
pti_task: using 2 dma channel
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
Validity = 0x0001 Mode = 0x0000
Validity = 0x0003 Mode = 0x0000
cx24116_demod_detect > socket-1: i2c-0 addr 0x5
cx24116_demod_detect: Detected cx24116
cx24116_demod_detect <
found cx24116 on socket socket-1
cx24116_demod_attach >
cx24116_register_frontend
fw_name dvb-fe-cx24116.fw
useLNB 2
useUnknwon 1
fw_name dvb-fe-cx24116.fw - dvb-fe-cx24116.fw
lnb_enable_pin 844ae6b0
DVB: registering adapter 0 frontend 0 (Conexant cx24116 DVB-S2)...
cx24116_demod_attach <
Free session: 0
Using session 0
pti_hal_get_new_descrambler (40000) >
pti_hal_get_new_descrambler (40001) >
pti_hal_get_new_descrambler (40002) >
pti_hal_get_new_descrambler (40003) >
pti_hal_get_new_descrambler (40004) >
pti_hal_get_new_descrambler (40005) >
pti_hal_get_new_descrambler (-8) >
pti_hal_get_new_descrambler (-8) >
Descrambler Handler = 40000
1: DeviceContext 8b8ae610, DvbDemux 8b8ae914, DmxDevice 8b8aeafc
ptiInit context = 8b8ae610, demux = 8b8ae914
Free session: 1
Using session 1
pti_hal_get_new_descrambler (41000) >
pti_hal_get_new_descrambler (41001) >
pti_hal_get_new_descrambler (41002) >
pti_hal_get_new_descrambler (41003) >
pti_hal_get_new_descrambler (41004) >
pti_hal_get_new_descrambler (41005) >
pti_hal_get_new_descrambler (-8) >
pti_hal_get_new_descrambler (-8) >
Descrambler Handler = 41000
2: DeviceContext 8b8aeb98, DvbDemux 8b8aee9c, DmxDevice 8b8af084
ptiInit context = 8b8aeb98, demux = 8b8aee9c
convert_source(): invalid frontend source (2)
Free session: 2
Using session 2
pti_hal_get_new_descrambler (42000) >
pti_hal_get_new_descrambler (42001) >
pti_hal_get_new_descrambler (42002) >
pti_hal_get_new_descrambler (42003) >
pti_hal_get_new_descrambler (42004) >
pti_hal_get_new_descrambler (42005) >
pti_hal_get_new_descrambler (-8) >
pti_hal_get_new_descrambler (-8) >
Descrambler Handler = 42000
3: DeviceContext 8b8af120, DvbDemux 8b8af424, DmxDevice 8b8af60c
ptiInit context = 8b8af120, demux = 8b8af424
convert_source(): invalid frontend source (3)
pti_hal_get_new_descrambler (-2) >
pti_hal_get_new_descrambler (-2) >
pti_hal_get_new_descrambler (-2) >
pti_hal_get_new_descrambler (-2) >
pti_hal_get_new_descrambler (-2) >
pti_hal_get_new_descrambler (-2) >
pti_hal_get_new_descrambler (-2) >
pti_hal_get_new_descrambler (-2) >
Descrambler Handler = -2
stm_v4l2_register_driver: driver 'Linux DVB Overlay' registered
OSDEV_LinkDevice - /dev/allocator, Major 245, Minor 0
AllocatorLoadModule : Allocator device loaded
Switching Preprocessor clock to full speed.
Platform STx7109 - cut 3
OSDEV_LinkDevice - /dev/h264pp, Major 246, Minor 0
H264ppLoadModule : H264pp device loaded
[simu_button] initializing ...
[simu_button] allocating and registering button device
input: TDT RC event driver as /devices/virtual/input/input0
zram: Creating 1 devices ...
Setting up swapspace version 1, size = 16773120 bytes
UUID=68392b8b-4f78-44f3-a663-67d0efc95bf4
ALSA: Restoring mixer settings...
No state is present for card STx7109
Found hardware: "STx7109" "" "" "" ""
Hardware is initialized using a generic method
No state is present for card STx7109
No state is present for card MIXER0
rm: can't remove '/dev/rc': No such file or directory
Found hardware: "Pseudo Mixer" "Pseudo Mixer" "" "" ""
Hardware is initialized using a generic method
[evremote2] Model: 'cuberevo-mini'
[evremote2] vBoxType: 12 (cuberevo-mini)
[evremote2] Input device name: "TDT RC event driver"
[evremote2] Remote selected: Cuberevo RemoteControl
[evremote2] RemoteControl Map:
             Keyname  Keyword  KeyCode
--------------------------------------
              KEY_F1  -  00  -   59
              KEY_F2  -  01  -   60
              KEY_F3  -  02  -   61
                INFO  -  03  -  358
               RADIO  -  04  -  385
            PREVIOUS  -  05  -  412
                 EPG  -  06  -  365
              RECORD  -  07  -  167
           FAVORITES  -  08  -  364
               MEDIA  -  09  -  226
             STANDBY  -  0A  -  116
              KEY_F5  -  0B  -   63
                MUTE  -  0C  -  113
             ARCHIVE  -  0D  -  361
                   0  -  10  -   11
                   1  -  11  -    2
                   2  -  12  -    3
                   3  -  13  -    4
                   4  -  14  -    5
                   5  -  15  -    6
                   6  -  16  -    7
No state is present for card MIXER0
                   7  -  17  -    8
                   8  -  18  -    9
                   9  -  19  -   10
                  UP  -  1A  -  103
                DOWN  -  1B  -  108
               RIGHT  -  1C  -  106
                LEFT  -  1D  -  105
              REWIND  -  1E  -  168
                  OK  -  1F  -  352
                PLAY  -  20  -  207
         FASTFORWARD  -  21  -  208
                STOP  -  22  -  128
                SLOW  -  23  -  409
               AGAIN  -  24  -  129
               PAUSE  -  25  -  119
                MENU  -  26  -  139
                EXIT  -  27  -  174
              KEY_F7  -  28  -   65
        KEY_BOOMARKS  -  29  -  156
                 RED  -  2A  -  398
                BLUE  -  2B  -  401
              KEY_F8  -  2C  -   66
               GREEN  -  2D  -  399
              YELLOW  -  2E  -  400
               AUDIO  -  2F  -  392
            SUBTITLE  -  30  -  370
                TEXT  -  31  -  388
           CHANNELUP  -  32  -  402
         CHANNELDOWN  -  33  -  403
            VOLUMEUP  -  34  -  115
          VOLUMEDOWN  -  35  -  114
                 WWW  -  36  -  150
--------------------------------------
[evremote2] Supports Long KeyPress: yes
vm.dirty_writeback_centisecs = 300
vm.dirty_background_ratio = 1
vm.dirty_ratio = 60
[evremote2 cuberevo] Period = 10, delay = 120
getVersion: : Bad file descriptor
[evremote2 cuberevo] micom version = 694197418
[evremote2] Error in device initialization
Configuring packages on first boot....
 (This may take several minutes. Please do not power off the machine.)
update-rc.d: /etc/init.d/run-postinsts exists during rc.d purge (continuing)
 Removing any system startup links for run-postinsts ...
  /etc/rcS.d/S99run-postinsts

INIT: Entering runlevel: 3

Configuring network interfaces... ip: RTNETLINK answers: File exists
udhcpc: option -h NAME is deprecated, use -x hostname:NAME
udhcpc (v1.24.1) started
Sending discover...
Sending select for 192.168.10.8...
Sending select for 192.168.10.8...
Sending select for 192.168.10.8...
Lease of 192.168.10.8 obtained, lease time 86400
/etc/udhcpc.d/50default: Adding DNS 198.153.192.53
/etc/udhcpc.d/50default: Adding DNS 198.153.194.50
/etc/udhcpc.d/50default: Adding DNS 199.85.126.20
ip: SIOCGIFFLAGS: No such device
Starting system message bus: dbus.
Starting Dropbear SSH server: Generating key, this may take a while...
Public key portion is:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCRSZ8QAWZ9JUr5IB2HDVGT6wf7T5eHEqQToxU2NFdiAM8x7IhbXlx9FVLu8f21lWMucwQv9J2gRwIzpOxa49CVSgqKkPXklSrcM9wrt1td3k5P6kteemT4WmX96XalzJVqWlu8TeIeLIU2luwVWitZJR65JLOmGRSCQ9AFflTwIw== root@cuberevo_mini
Fingerprint: md5 b6:f4:93:ae:32:ea:a5:b4:17:f8:7b:a6:21:fb:3f:6c
dropbear.
Starting rpcbind daemon...done.
Mounting remote filesystems...
starting statd: done
Current year: 2000 older than 2018 !
Trying to set correct date/time with a maximum timeout of 5 seconds...
18 Feb 22:17:03 ntpdate[1212]: step time server 96.244.96.25 offset 603843269.593860 sec
starting Busybox Periodic Command Scheduler: crond... done.
* starting UPnP client: djmount... crond[1218]: crond (busybox 1.24.1) started, log level 8

done.
Starting internet superserver: inetd.
Starting minidlna minidlna
[2019/02/18 22:17:08] minidlna.c:612: error: Media directory "/media/hdd/movie/" not accessible [No such file or directory]
done
starting 8 nfsd kernel threads: rpc.nfsd: unable to set any sockets for nfsd
Starting ntpd: done
Starting Samba: smbd nmbd.
Starting syslogd/klogd: done
 * Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon
   ...done.
Starting astra
/usr/bin/enigma2.sh: line 8: can't create /dev/vfd: No such device or address
/dev/dvb/adapter0/video0: Device or resource busy
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 10
ENIGMA_DEBUG_LVL=3
[MAIN] executing main
no profile data available
close failed in file object destructor:
IOError: [Errno 5] Input/output error
Stopping minidlna minidlna
stopped process in pidfile '/var/run/minidlna/minidlna.pid' (pid 1242)
done
Cannot open /dev/vfd
No such device or address
getVersion: Bad file descriptor
Cannot open /dev/vfd
No such device or address
Set compatibility mode: Bad file descriptor
SetLED: Bad file descriptor

**Comment by backup1977** [comment]
I took an old micom.ko from an old image, and rename it in cuberevo_micom.ko and swapped.
then everything worked again, front display ok
Remote control ok again

**Comment by backup1977** [comment]
I do not understand now, with audioniek his image starts the cuberevo_micom quite normally
Did he protect that, against other image?

**Comment by backup1977** [comment]
CubeRevo Mini II: add kernel RTC support

https://github.com/Audioniek/buildsystem/commit/73439693a958df5200568dfcfaddd94dfde2f8e7

**Comment by sid8796** [comment]
I can only correct in the evening for cuberevo * defconfig

**Comment by backup1977** [comment]
Ok

**Comment by backup1977** [comment]
it works again thanks
